### ISSUE TITLE
Unreachable code

### ISSUE THREAD

**Issue by Gaurav192** [TatsuUkraine/flutter_sticky_infinite_list#10]
Facing issue while compiling release apk for arm64.
Logs while building [example app](https://github.com/TatsuUkraine/flutter_sticky_infinite_list_example).
https://del.dog/flutter_sticky_infinite_list.sql

**Comment by TatsuUkraine** [comment]
Thank you for reporting this. I'm getting same errors currently, trying to figure out what is wrong. I tried to import package into other project - no errors there

**Comment by TatsuUkraine** [comment]
@Gaurav192 found the problem, will provide fix soon) thank you again for reporting this issue)

**Comment by TatsuUkraine** [comment]
@Gaurav192 issue is fixed in new package version, also example app yaml update with new version
