### ISSUE TITLE
Erro => scrollDirection: Axis.horizontal

### ISSUE THREAD

**Issue by MarceloRab** [TatsuUkraine/flutter_sticky_infinite_list#13]
The following NoSuchMethodError was thrown building _StickySliverListItem<int>(dependencies:
I/flutter (31517): [MediaQuery], state: _StickySliverListItemState<int>#030fb):
I/flutter (31517): The method 'addListener' was called on null.
I/flutter (31517): Receiver: null
I/flutter (31517): Tried calling: addListener(Closure: () => void from Function 'markNeedsPaint':.)

**Comment by TatsuUkraine** [comment]
@MarceloRab could you provide code sample?

**Comment by MarceloRab** [comment]
class MyEvestsListDayScroll extends StatefulWidget {


  @override
  _MyEvestsListDayScrollState createState() => _MyEvestsListDayScrollState();
}

class _MyEvestsListDayScrollState extends State<MyEvestsListDayScroll> {
  final String className = "_ _MyEvestsListDayScrollState ___ ...  ";
  int minCount = 0;
  int maxCount = 1;
  CompromissoBloc _compromissoBloc;

  //DateTime dayEvents;

  @override
  void initState() {
    //maxCount = widget.listEventDay.length;
    //maxCount = _compromissoBloc.eventsDay.length;
    _compromissoBloc = HomeModule.to.bloc<CompromissoBloc>();

    super.initState();
  }

  @override
  Widget build(BuildContext context) {
   
    return StreamBuilder<DateTime>(
        stream: _compromissoBloc.dayEscolhidoStream,
        builder: (context, snapshot) {
          if (!snapshot.hasData)
            return Center(
              child: CircularProgressIndicator(),
            );
          else
            return InfiniteList(
                // scrollDirection: Axis.horizontal,
                minChildCount: minCount,
                maxChildCount: maxCount,
                anchor: 0.0,
                builder: (BuildContext context, int index) {
                  return InfiniteListItem(
                    initialHeaderBuild: true,
                    minOffsetProvider: (StickyState<int> state) => 50,
                    //headerAlignment: HeaderAlignment.bottomLeft,
                    headerStateBuilder:
                        (BuildContext context, StickyState<int> state) {
                      return Container(
                        decoration: BoxDecoration(
                          shape: BoxShape.circle,
                          color: Colors.orange.withOpacity(state.position != 0
                              ? 1 - (state.position)
                              : (1 - state.position).abs()),
                          boxShadow: [
                            BoxShadow(
                                color: Colors.black12,
                                blurRadius: 2,
                                offset: Offset(2.0, 3.0),
                                spreadRadius: 2.0)
                          ],
                        ),
                        alignment: Alignment.center,
                        margin: EdgeInsets.only(left: 6, top: 20),
                        padding: EdgeInsets.all(12),
                        width: 70,
                        height: 80,
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          children: <Widget>[
                            Text(
                              //"${MyDateHelper.setDiaDate(_compromissoBloc.eventsFullList[index].id)}",
                              "${MyDateHelper.setDiaDate(snapshot.data)}",
                              style: TextStyle(
                                  fontSize: 20,
                                  fontFamily: 'Roboto Mono',
                                  fontWeight: FontWeight.bold),
                            ),
                            Text(
                              //"${MyDateHelper.setDiaDate(_compromissoBloc.eventsFullList[index].id)}",

                              "${MyDateHelper.setMonthCalendar(
                                date: snapshot.data,
                              ).substring(0, 3)}",

                              style: TextStyle(
                                fontSize: 18,
                                fontFamily: 'Roboto Mono',
                              ),
                            ),
                          ],
                        ),
                      );
                    },
                    contentBuilder: (BuildContext context) {
                      return Container(
                        decoration: BoxDecoration(
                          color: Colors.blueAccent,
                            borderRadius: BorderRadius.all(
                                Radius.circular(20))),
                        height:
                            (34 * _compromissoBloc.eventsDay.length).toDouble(),
                        margin: EdgeInsets.only(left: 50, top: 10, right: 10),
                        width: MediaQuery.of(context).size.width - 60,
                        child: Align(
                          alignment: Alignment.topLeft,
                          child: Column(
                            //mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.start,

                            children:
                                _compromissoBloc.eventsDay.map<Widget>((event) {
                              return Container(
                                margin: EdgeInsets.only(left: 40, top: 10),
                                child: Text(
                                  "Content ${event as String}",
                                  style: TextStyle(
                                      color: Colors.white, fontSize: 18),
                                ),
                              );
                            }).toList(),
                          ),
                        ),
                      );
                    },
                  );
                });
        });
  }
}

**Comment by MarceloRab** [comment]
thanks in advance for the support

**Comment by TatsuUkraine** [comment]
@MarceloRab sure - https://github.com/TatsuUkraine/flutter_sticky_infinite_list_example this is an example app, you can switch horizontal and vertical list there in left sidenav

**Comment by MarceloRab** [comment]
Thank you. I'm going to study and ask for help if you need it.

**Comment by TatsuUkraine** [comment]
@MarceloRab btw, I noticed that you going to render just 1 element with a bunch of data inside, so you can try to use just SingleChildScrollView with this widget inside https://github.com/TatsuUkraine/flutter_sticky_infinite_list/blob/master/lib/widget.dart#L363

**Comment by MarceloRab** [comment]
That's right, I'm in testing mode. Already tested with many elements and in vertical mode flowed correctly.

**Comment by TatsuUkraine** [comment]
@MarceloRab btw, could you also provide `flutter doctor` info?

**Comment by MarceloRab** [comment]
One moment please.

**Comment by TatsuUkraine** [comment]
@MarceloRab ok, I think I found where problem is. Try to specify ScrollController() in InfiniteList as tmp solution. I'm going to investigate this further, but it seems that Flutter doesn't create controller for scroll axis horizontal

**Comment by TatsuUkraine** [comment]
Which is strange, since it creates controller for vertical scroll by default, if it's not specified

**Comment by MarceloRab** [comment]
@TatsuUkraine My list is inside a NotificationListener <ScrollNotification>. That's why I don't add a ScrollController (). But I will test as per your recommendation.

**Comment by TatsuUkraine** [comment]
@MarceloRab it's just a temp if you need to make it work quick) I will push new release with fix for this issue tomorrow

**Comment by TatsuUkraine** [comment]
@MarceloRab Or you can use this branch for now https://github.com/TatsuUkraine/flutter_sticky_infinite_list/tree/position-listener-bug

**Comment by MarceloRab** [comment]
@TatsuUkraine Everything was ok. As use in a PageView, there is no need for horizontal movement. But his orientation of not setting controller = null solved the problem in my tests. Thank you so.

**Comment by TatsuUkraine** [comment]
@MarceloRab new version is available (1.2.3) on pub.dart. This version contains fixes for this issue with a horizontal scroll. Also it fixes standalone `StickyListItem` usage inside `SingleChildScrollView`.

Also [Example project] (https://github.com/TatsuUkraine/flutter_sticky_infinite_list_example) was updated with an example of `StickyListItem` usage
