### ISSUE TITLE
What is the best approach to stick one widget on scroll

### ISSUE THREAD

**Issue by ycgambo** [TatsuUkraine/flutter_sticky_infinite_list#17]
I want to stick the pink area. Should I use CustomScrollView instead of Scaffold? What are the features that CustomScrollView provides but Scaffold doesn't?

![image](https://user-images.githubusercontent.com/23355083/65162195-7624f480-da6b-11e9-8839-8e23de0abaa2.png)

**Comment by TatsuUkraine** [comment]
CustomScrollView is just one of the many scrolling widgets (like SliverList or singlechildscrollview), so it's not a replacement for scaffold in any mean, it's just a different widget

As for your example. Recently I added example, how to use StickyListItem as standalone widget and also I updated example project with this example. https://github.com/TatsuUkraine/flutter_sticky_infinite_list/blob/master/README.md#need-more-override

**Comment by TatsuUkraine** [comment]
@ycgambo But in your particular example I'm not sure that you actually need to use my package. You can simply place scrolling widget below pink are

**Comment by TatsuUkraine** [comment]
@ycgambo so like an example it could be `Column` with 3 children, first one - row above pink widget, second one - will be pink one. And third one - flexible with flex === 1 and child - grid view (or maybe third-party) widget

**Comment by TatsuUkraine** [comment]
In that way scroll area will be section after pink widget, so pink widget will behave like `sticky` since it won't be scrolled

**Comment by ycgambo** [comment]
Thank you, these info really helps a lot. I'll try it out. thanks.

**Comment by ycgambo** [comment]
Sorry, I didn't make myself clear.

Here is a real app screen record. 

![2019-09-19 21 45 31](https://user-images.githubusercontent.com/23355083/65249630-e0e73600-db26-11e9-85df-a0ce7894d7de.gif)

**Comment by TatsuUkraine** [comment]
Probably you can achieve this type of behavior with SliverList + SliverAppBar + TabBar. Obviously you will need to provide own sized widget. At least from what I see in a screenrecord , I think it will be enough to use widget, that I listed above)

**Comment by ycgambo** [comment]
Thanks. I’ll try it out.
