### ISSUE TITLE
What should I watch or what method could I use to make a request for more data

### ISSUE THREAD

**Issue by jamesmenera** [TatsuUkraine/flutter_sticky_infinite_list#18]
I apologize if I am just missing something, but how do I know that I am getting towards on end of my rendered data and to trigger a request for more? Read through the code base and it was still not clear what should trigger to make a call

**Comment by TatsuUkraine** [comment]
You need to load more data on scroll end or when container with header goes outside of viewport?

**Comment by TatsuUkraine** [comment]
@jamesmenera ?

**Comment by TatsuUkraine** [comment]
@jamesmenera do you still need any help with this issue?) if not, I will close it later today

**Comment by TatsuUkraine** [comment]
closing this issue, since didn't get any response. @jamesmenera feel free to reach me or open issue if you need any help

**Comment by tudor07** [comment]
I have the same question.
I use a `NotificationListener` to listen for `ScrollEndNotification`.
To check whether user reached the top I use this:
```
 if (_scrollCtrl.position.pixels.toInt() ==
          _scrollCtrl.position.minScrollExtent.toInt())
```

But I get this error:
```
Unhandled Exception: Unsupported operation: Infinity or NaN toInt
```

**Comment by TatsuUkraine** [comment]
@tudor07 according to docs `minScrollExtent` can actually be infinite, if a scroll is infinite. If you want to load data when a user scrolls to the end of the scroll - you need to make it finite, which means that you need to define max pos/neg params, if you using `InfiniteList` widget from this package, or use your delegate with items count property, hard to say without actual code)

**Comment by tudor07** [comment]
@TatsuUkraine thanks, it worked with specifying `negChildCount` and `posChildCount`
