### ISSUE TITLE
Esay fix : Physics attributes !

### ISSUE THREAD

**Issue by EArminjon** [TatsuUkraine/flutter_sticky_infinite_list#22]
Hi,

Please allow developpers to use a customized value for the CustomScrollView 'physics' (Ligne 250 widget.dart) :

```dart
Widget build(BuildContext context) => CustomScrollView(
    physics: AlwaysScrollableScrollPhysics(),
    controller: widget.controller,
    center: widget._centerKey,
    slivers: _slivers,
    reverse: widget.reverse,
    anchor: widget.anchor,
    cacheExtent: widget.cacheExtent,
    scrollDirection: widget.scrollDirection,
  );
```

In my case I should always be able to scroll my view. With that, user can scroll to refresh the data :) !

**Comment by TatsuUkraine** [comment]
will do)

**Comment by EArminjon** [comment]
Do you want a pull request ?

**Comment by TatsuUkraine** [comment]
not necessary) I will try to publish a new version when I get time, it will be in a few hours

**Comment by TatsuUkraine** [comment]
@EArminjon changes are in 1.3.0
