### ISSUE TITLE
Adding items at the top makes the list jump

### ISSUE THREAD

**Issue by tudor07** [TatsuUkraine/flutter_sticky_infinite_list#33]
When I add more items at the top of the list I want the list to stay in place and user should continue scrolling upward to see the content. Right now after I add items at the top the list instantly jumps to the first item.

**Comment by TatsuUkraine** [comment]
hello. Thank you for the issue. Could you provide screenshot of this behavior and maybe some code how this can be reproduced?

**Comment by TatsuUkraine** [comment]
@tudor07

**Comment by tudor07** [comment]
@TatsuUkraine My mistake, I needed to use `direction: InfiniteListDirection.multi` to get this feature (by default it's `InfiniteListDirection.single`).
