### ISSUE TITLE
GridView or GridSliver as Child

### ISSUE THREAD

**Issue by vauvenal5** [TatsuUkraine/flutter_sticky_infinite_list#34]
Hi,

is it possible to add a GridView or a GridSliver as the child of your infiniteList?

Cheers!

**Comment by TatsuUkraine** [comment]
Hello.

The problem is that `GridView` is a scrollable widget (for example `InfiniteList` widget uses `CustomScrollView`) and `GridSliver` is sliver (scroll) item. So overall it's possible, BUT fortunately, it won't be the quite best solution))

What actually you want to achieve? Maybe you can provide a screenshot with an example?

**Comment by vauvenal5** [comment]
![Screenshot_1593817322](https://user-images.githubusercontent.com/1935503/86500513-e948ee80-bd91-11ea-9ade-0bc7e2955b7f.png)

I am trying to make an image view where images are sorted by date modified (or any other category) and within this category they are displayed in a grid. The issue I am experiencing with the current library (flutter_sticky_header) is that all the headers are kept in the list which becomes a problem when displaying a lot of images.

**Comment by TatsuUkraine** [comment]
so the case here that `flutter_sticky_header` is focused on a finite list of categories with potentially infinite content within the category. My package, on the other hand, is focused on a potentially infinite list of categories with a finite content within the category.

So if you want to use my package to accomplish your task - you actually not necessarily need `GridSliver` to build category content. Like, potentially, you can use GridView with [shrinkWrap](https://api.flutter.dev/flutter/widgets/GridView/shrinkWrap.html), but I'm not sure if you get any performance benefit from it compared to just using [Wrap](https://api.flutter.dev/flutter/widgets/Wrap-class.html) widget as a category content

**Comment by vauvenal5** [comment]
Thank you for your suggestion. I will look into it and give it a try.

**Comment by vauvenal5** [comment]
Your library with the suggested solution uses about 30% less memory, which is good. Performance seems to be a little bit better, however, I have not done extensive comparisons yet. 

If I have to guess, I would say your library will perform better in cases where there are a lot of categories with limited amount of content per category whereas `flutter_sticky_header` will perform better in cases with a limited amount of categories with a lot of content each.

I decided to default to your library since it consumes less memory in my testcase, however, I do intend to perform some more tests in the future.

Thx for your help.

**Comment by TatsuUkraine** [comment]
I'm glad it helped) let me know if you get any problems)
