### ISSUE TITLE
Not working with Flutter 1.20 and higher

### ISSUE THREAD

**Issue by tudor07** [TatsuUkraine/flutter_sticky_infinite_list#35]
Not working with Flutter 1.17.5 (which is currently on `dev` channel)

```
/C:/dev/flutter/.pub-cache/hosted/pub.dartlang.org/sticky_infinite_list-2.1.0+2/lib/render.dart:50:11: Error: No named parameter with the name 'overflow'.
          overflow: overflow,
          ^^^^^^^^
```

Looks like `overflow` param was removed from [RenderStack](https://api.flutter.dev/flutter/rendering/RenderStack-class.html)

**Comment by TatsuUkraine** [comment]
Thanks for an update. I will try to push new dev release with these changes soon

**Comment by mrpvb-pvbk** [comment]
+1

**Comment by TatsuUkraine** [comment]
@tudor07 could you provide flutter version that you currently using? since currently 1.17.5 is in the stable channel and package works fine there

**Comment by TatsuUkraine** [comment]
@mrpvb-pvbk if you have the same issue, could you provide your Flutter version as well?

**Comment by mrpvb-pvbk** [comment]
> @mrpvb-pvbk if you have the same issue, could you provide your Flutter version as well?

At beta channel 1.20 same error

**Comment by TatsuUkraine** [comment]
I've published v3-dev, so the issue should be solved for dev and beta flutter channels. I will keep this issue opened until flutter will publish the next stable release with these changes. Just keep in mind that there is a chance that these changes could be removed from Flutter's stable release (at least according to git history these changes already was reverted once and then this revert was reverted again)

**Comment by tudor07** [comment]
`3.0.0-dev.2` works fine for me 👍

**Comment by TatsuUkraine** [comment]
@tudor07 @mrpvb-pvbk version 3 is live, so you can update package version now
