### ISSUE TITLE
Expand / collapse content

### ISSUE THREAD

**Issue by thegrxp** [TatsuUkraine/flutter_sticky_infinite_list#44]
**Describe the behavior you'd like to achieve**
Hello, 
I want to expand / collapse items attached to a header when I click on the header. I have trouble to achieve this result as the builder of InfiniteList require an InfiniteListItem<int> and not a widget.
Thank you for your help and for this amazing lib

**Comment by TatsuUkraine** [comment]
Hello) thank you)

Do you want to have infinite list in both directions or just one particular?

**Comment by TatsuUkraine** [comment]
I'm asking because there might be couple of options, how you can solve your issue, so just trying to figure out which one will be easiest one in your particular context

**Comment by thegrxp** [comment]
Thank you for your help ! I would like to do it in one direction

**Comment by TatsuUkraine** [comment]
if so you actually have 2 options:

1. use [StickyListItem](https://pub.dev/documentation/sticky_infinite_list/latest/widget/StickyListItem-class.html), which is a regular widget, within any scrollable widget. It can literally any scrollable widget like SingleChildScrollable..., ListView, CustomScrollWidget etc. StickyListItem requires only header, content, and index (any value), all rest is optional. You can find [example in the doc](https://github.com/TatsuUkraine/flutter_sticky_infinite_list#need-more-override) or in the [example project](https://github.com/TatsuUkraine/flutter_sticky_infinite_list_example/blob/master/lib/main.dart#L565)

2. extend or implement [InfiniteListItem](https://pub.dev/documentation/sticky_infinite_list/latest/widget/InfiniteListItem-class.html). Example with extension can be [found here](https://github.com/TatsuUkraine/flutter_sticky_infinite_list#available-for-override) You can provide any values you want there and then you will be able to use your custom implementation within InfiniteList widget.

**Comment by thegrxp** [comment]
Thanks, I'll look into that !

**Comment by TatsuUkraine** [comment]
I don't know how you want to persist collapsible state, but for example, for option #1 it may look something like this:

```dart
class SomeItem extends StatefulWidget {

  @override
  _SomeItemState createState() => _SomeItemState();
}

class _SomeItemState extends State<SomeItem> {
    bool _collapsed = false;

    Widget build(_) {
        return StickyListItem<String>(
          header: GestureDetector(
            onTap: () { setState(() {_collapsed = !_collapsed}); },
            child: ///your header,
          ),
          content: _collapsed 
             ? ///your collapsed content,
             : /// regular content
          itemIndex: "some-index",
        );
    }
}
```

and then you can use `SomeItem` in your ListView for example

**Comment by TatsuUkraine** [comment]
for option #2 - you can define value notifier during `InfiniteListItem` extend (it has methods like `initState` or `dispose` if you need) and do similar like in option 1 - track gesture on header, update ValueNotifier, build content with [ValueListenableBuilder](https://api.flutter.dev/flutter/widgets/ValueListenableBuilder-class.html)

**Comment by TatsuUkraine** [comment]
so there are few variants) hard to say which one fits for you better) all up to you here)

**Comment by thegrxp** [comment]
Thank's again, I'll go with #2
