### ISSUE TITLE
How to detect which index is visible?

### ISSUE THREAD

**Issue by desmeit** [TatsuUkraine/flutter_sticky_infinite_list#61]
Is there a way to detect which Item is visible if InfiniteListItems has different sizes?

**Comment by TatsuUkraine** [comment]
You can use flutter for that I think, or maybe a package that will report whenever widget will be visible within the viewport

**Comment by pickywawa** [comment]
If you use sticky header you can :

`
InfiniteListItem(

          headerStateBuilder: (context, state) {
             if (state.sticky) {
                Future(() => // call index change function);
             }
             return headerWidget;
         }
 )

`
